package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CategoryValue generated by hbm2java
 */
public class CategoryValue implements java.io.Serializable {
    
    private static final long serialVersionUID = 1L;

    private long categoryValueId;

    private String value;

    private Set<Observation> observations = new HashSet<Observation>(0);

    public CategoryValue() {
    }

    public CategoryValue(long categoryValueId, String value) {
        this.categoryValueId = categoryValueId;
        this.value = value;
    }

    public CategoryValue(long categoryValueId, String value, Set<Observation> observations) {
        this.categoryValueId = categoryValueId;
        this.value = value;
        this.observations = observations;
    }

    public long getCategoryValueId() {
        return this.categoryValueId;
    }

    public void setCategoryValueId(long categoryValueId) {
        this.categoryValueId = categoryValueId;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Set<Observation> getObservations() {
        return this.observations;
    }

    public void setObservations(Set<Observation> observations) {
        this.observations = observations;
    }

}
