package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CompositePhenomenon generated by hbm2java
 */
public class CompositePhenomenon implements java.io.Serializable {

	private long compositePhenomenonId;
	private String identifier;
	private String description;
	private Set requests = new HashSet(0);
	private Set observableProperties = new HashSet(0);

	public CompositePhenomenon() {
	}

	public CompositePhenomenon(long compositePhenomenonId, String identifier) {
		this.compositePhenomenonId = compositePhenomenonId;
		this.identifier = identifier;
	}

	public CompositePhenomenon(long compositePhenomenonId, String identifier,
			String description, Set requests, Set observableProperties) {
		this.compositePhenomenonId = compositePhenomenonId;
		this.identifier = identifier;
		this.description = description;
		this.requests = requests;
		this.observableProperties = observableProperties;
	}

	public long getCompositePhenomenonId() {
		return this.compositePhenomenonId;
	}

	public void setCompositePhenomenonId(long compositePhenomenonId) {
		this.compositePhenomenonId = compositePhenomenonId;
	}

	public String getIdentifier() {
		return this.identifier;
	}

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getRequests() {
		return this.requests;
	}

	public void setRequests(Set requests) {
		this.requests = requests;
	}

	public Set getObservableProperties() {
		return this.observableProperties;
	}

	public void setObservableProperties(Set observableProperties) {
		this.observableProperties = observableProperties;
	}

}
