package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CountValue generated by hbm2java
 */
public class CountValue implements java.io.Serializable {

	private long countValueId;
	private long value;
	private Set observations = new HashSet(0);

	public CountValue() {
	}

	public CountValue(long countValueId, long value) {
		this.countValueId = countValueId;
		this.value = value;
	}

	public CountValue(long countValueId, long value, Set observations) {
		this.countValueId = countValueId;
		this.value = value;
		this.observations = observations;
	}

	public long getCountValueId() {
		return this.countValueId;
	}

	public void setCountValueId(long countValueId) {
		this.countValueId = countValueId;
	}

	public long getValue() {
		return this.value;
	}

	public void setValue(long value) {
		this.value = value;
	}

	public Set getObservations() {
		return this.observations;
	}

	public void setObservations(Set observations) {
		this.observations = observations;
	}

}
