package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CountValue generated by hbm2java
 */
public class CountValue implements java.io.Serializable {
    
    private static final long serialVersionUID = 1L;

    private long countValueId;

    private int value;

    private Set<Observation> observations = new HashSet<Observation>(0);

    public CountValue() {
    }

    public CountValue(long countValueId, int value) {
        this.countValueId = countValueId;
        this.value = value;
    }

    public CountValue(long countValueId, int value, Set<Observation> observations) {
        this.countValueId = countValueId;
        this.value = value;
        this.observations = observations;
    }

    public long getCountValueId() {
        return this.countValueId;
    }

    public void setCountValueId(long countValueId) {
        this.countValueId = countValueId;
    }

    public int getValue() {
        return this.value;
    }

    public void setValue(int value) {
        this.value = value;
    }

    public Set<Observation> getObservations() {
        return this.observations;
    }

    public void setObservations(Set<Observation> observations) {
        this.observations = observations;
    }

}
