/**
 * Copyright (C) 2013
 * by 52 North Initiative for Geospatial Open Source Software GmbH
 *
 * Contact: Andreas Wytzisk
 * 52 North Initiative for Geospatial Open Source Software GmbH
 * Martin-Luther-King-Weg 24
 * 48155 Muenster, Germany
 * info@52north.org
 *
 * This program is free software; you can redistribute and/or modify it under
 * the terms of the GNU General Public License version 2 as published by the
 * Free Software Foundation.
 *
 * This program is distributed WITHOUT ANY WARRANTY; even without the implied
 * WARRANTY OF MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program (see gnu-gpl v2.txt). If not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA or
 * visit the Free Software Foundation web page, http://www.fsf.org.
 */
package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * FeatureOfInterestType generated by hbm2java
 */
public class FeatureOfInterestType implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    private long featureOfInterestTypeId;

    private String featureOfInterestType;

//    private Set<Procedure> procedures = new HashSet<Procedure>(0);
//
//    private Set<FeatureOfInterest> featureOfInterests = new HashSet<FeatureOfInterest>(0);

    public FeatureOfInterestType() {
    }

//    public FeatureOfInterestType(long featureOfInterestTypeId, String featureOfInterestType) {
//        this.featureOfInterestTypeId = featureOfInterestTypeId;
//        this.featureOfInterestType = featureOfInterestType;
//    }
//
//    public FeatureOfInterestType(long featureOfInterestTypeId, String featureOfInterestType, Set<Procedure> procedures,
//            Set<FeatureOfInterest> featureOfInterests) {
//        this.featureOfInterestTypeId = featureOfInterestTypeId;
//        this.featureOfInterestType = featureOfInterestType;
//        this.procedures = procedures;
//        this.featureOfInterests = featureOfInterests;
//    }

    public long getFeatureOfInterestTypeId() {
        return this.featureOfInterestTypeId;
    }

    public void setFeatureOfInterestTypeId(long featureOfInterestTypeId) {
        this.featureOfInterestTypeId = featureOfInterestTypeId;
    }

    public String getFeatureOfInterestType() {
        return this.featureOfInterestType;
    }

    public void setFeatureOfInterestType(String featureOfInterestType) {
        this.featureOfInterestType = featureOfInterestType;
    }

//    public Set<Procedure> getProcedures() {
//        return this.procedures;
//    }
//
//    public void setProcedures(Set<Procedure> procedures) {
//        this.procedures = procedures;
//    }
//
//    public Set<FeatureOfInterest> getFeatureOfInterests() {
//        return this.featureOfInterests;
//    }
//
//    public void setFeatureOfInterests(Set<FeatureOfInterest> featureOfInterests) {
//        this.featureOfInterests = featureOfInterests;
//    }

}
