package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * FeatureOfInterestType generated by hbm2java
 */
public class FeatureOfInterestType implements java.io.Serializable {

	private long featureOfInterestTypeId;
	private String featureOfInterestType;
	private Set procedures = new HashSet(0);
	private Set featureOfInterests = new HashSet(0);

	public FeatureOfInterestType() {
	}

	public FeatureOfInterestType(long featureOfInterestTypeId,
			String featureOfInterestType) {
		this.featureOfInterestTypeId = featureOfInterestTypeId;
		this.featureOfInterestType = featureOfInterestType;
	}

	public FeatureOfInterestType(long featureOfInterestTypeId,
			String featureOfInterestType, Set procedures, Set featureOfInterests) {
		this.featureOfInterestTypeId = featureOfInterestTypeId;
		this.featureOfInterestType = featureOfInterestType;
		this.procedures = procedures;
		this.featureOfInterests = featureOfInterests;
	}

	public long getFeatureOfInterestTypeId() {
		return this.featureOfInterestTypeId;
	}

	public void setFeatureOfInterestTypeId(long featureOfInterestTypeId) {
		this.featureOfInterestTypeId = featureOfInterestTypeId;
	}

	public String getFeatureOfInterestType() {
		return this.featureOfInterestType;
	}

	public void setFeatureOfInterestType(String featureOfInterestType) {
		this.featureOfInterestType = featureOfInterestType;
	}

	public Set getProcedures() {
		return this.procedures;
	}

	public void setProcedures(Set procedures) {
		this.procedures = procedures;
	}

	public Set getFeatureOfInterests() {
		return this.featureOfInterests;
	}

	public void setFeatureOfInterests(Set featureOfInterests) {
		this.featureOfInterests = featureOfInterests;
	}

}
