package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * FeatureOfInterestType generated by hbm2java
 */
public class FeatureOfInterestType implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    private long featureOfInterestTypeId;

    private String featureOfInterestType;

    private Set<Procedure> procedures = new HashSet<Procedure>(0);

    private Set<FeatureOfInterest> featureOfInterests = new HashSet<FeatureOfInterest>(0);

    public FeatureOfInterestType() {
    }

    public FeatureOfInterestType(long featureOfInterestTypeId, String featureOfInterestType) {
        this.featureOfInterestTypeId = featureOfInterestTypeId;
        this.featureOfInterestType = featureOfInterestType;
    }

    public FeatureOfInterestType(long featureOfInterestTypeId, String featureOfInterestType, Set<Procedure> procedures,
            Set<FeatureOfInterest> featureOfInterests) {
        this.featureOfInterestTypeId = featureOfInterestTypeId;
        this.featureOfInterestType = featureOfInterestType;
        this.procedures = procedures;
        this.featureOfInterests = featureOfInterests;
    }

    public long getFeatureOfInterestTypeId() {
        return this.featureOfInterestTypeId;
    }

    public void setFeatureOfInterestTypeId(long featureOfInterestTypeId) {
        this.featureOfInterestTypeId = featureOfInterestTypeId;
    }

    public String getFeatureOfInterestType() {
        return this.featureOfInterestType;
    }

    public void setFeatureOfInterestType(String featureOfInterestType) {
        this.featureOfInterestType = featureOfInterestType;
    }

    public Set<Procedure> getProcedures() {
        return this.procedures;
    }

    public void setProcedures(Set<Procedure> procedures) {
        this.procedures = procedures;
    }

    public Set<FeatureOfInterest> getFeatureOfInterests() {
        return this.featureOfInterests;
    }

    public void setFeatureOfInterests(Set<FeatureOfInterest> featureOfInterests) {
        this.featureOfInterests = featureOfInterests;
    }

}
