package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.vividsolutions.jts.geom.Geometry;

/**
 * FeatureOfInterest generated by hbm2java
 */
public class FeatureOfInterest implements java.io.Serializable {

	private long featureOfInterestId;
	private FeatureOfInterestType featureOfInterestType;
	private String identifier;
	private Geometry geom;
	private String descriptionXml;
	private String url;
	private boolean samplingFeature;
	private Set observations = new HashSet(0);
	private Set featureOfInterestsForChildFeatureId = new HashSet(0);
	private Set featureOfInterestsForParentFeatureId = new HashSet(0);
	private Set resultTemplates = new HashSet(0);

	public FeatureOfInterest() {
	}

	public FeatureOfInterest(long featureOfInterestId,
			FeatureOfInterestType featureOfInterestType, boolean samplingFeature) {
		this.featureOfInterestId = featureOfInterestId;
		this.featureOfInterestType = featureOfInterestType;
		this.samplingFeature = samplingFeature;
	}

	public FeatureOfInterest(long featureOfInterestId,
			FeatureOfInterestType featureOfInterestType, String identifier,
			Geometry geom, String descriptionXml, String url,
			boolean samplingFeature, Set observations,
			Set featureOfInterestsForChildFeatureId,
			Set featureOfInterestsForParentFeatureId, Set resultTemplates) {
		this.featureOfInterestId = featureOfInterestId;
		this.featureOfInterestType = featureOfInterestType;
		this.identifier = identifier;
		this.geom = geom;
		this.descriptionXml = descriptionXml;
		this.url = url;
		this.samplingFeature = samplingFeature;
		this.observations = observations;
		this.featureOfInterestsForChildFeatureId = featureOfInterestsForChildFeatureId;
		this.featureOfInterestsForParentFeatureId = featureOfInterestsForParentFeatureId;
		this.resultTemplates = resultTemplates;
	}

	public long getFeatureOfInterestId() {
		return this.featureOfInterestId;
	}

	public void setFeatureOfInterestId(long featureOfInterestId) {
		this.featureOfInterestId = featureOfInterestId;
	}

	public FeatureOfInterestType getFeatureOfInterestType() {
		return this.featureOfInterestType;
	}

	public void setFeatureOfInterestType(
			FeatureOfInterestType featureOfInterestType) {
		this.featureOfInterestType = featureOfInterestType;
	}

	public String getIdentifier() {
		return this.identifier;
	}

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	public Geometry getGeom() {
		return this.geom;
	}

	public void setGeom(Geometry geom) {
		this.geom = geom;
	}

	public String getDescriptionXml() {
		return this.descriptionXml;
	}

	public void setDescriptionXml(String descriptionXml) {
		this.descriptionXml = descriptionXml;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public boolean isSamplingFeature() {
		return this.samplingFeature;
	}

	public void setSamplingFeature(boolean samplingFeature) {
		this.samplingFeature = samplingFeature;
	}

	public Set getObservations() {
		return this.observations;
	}

	public void setObservations(Set observations) {
		this.observations = observations;
	}

	public Set getFeatureOfInterestsForChildFeatureId() {
		return this.featureOfInterestsForChildFeatureId;
	}

	public void setFeatureOfInterestsForChildFeatureId(
			Set featureOfInterestsForChildFeatureId) {
		this.featureOfInterestsForChildFeatureId = featureOfInterestsForChildFeatureId;
	}

	public Set getFeatureOfInterestsForParentFeatureId() {
		return this.featureOfInterestsForParentFeatureId;
	}

	public void setFeatureOfInterestsForParentFeatureId(
			Set featureOfInterestsForParentFeatureId) {
		this.featureOfInterestsForParentFeatureId = featureOfInterestsForParentFeatureId;
	}

	public Set getResultTemplates() {
		return this.resultTemplates;
	}

	public void setResultTemplates(Set resultTemplates) {
		this.resultTemplates = resultTemplates;
	}

}
