package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

/**
 * GeographyColumns generated by hbm2java
 */
public class GeographyColumns implements java.io.Serializable {

	private GeographyColumnsId id;

	public GeographyColumns() {
	}

	public GeographyColumns(GeographyColumnsId id) {
		this.id = id;
	}

	public GeographyColumnsId getId() {
		return this.id;
	}

	public void setId(GeographyColumnsId id) {
		this.id = id;
	}

}
