package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

/**
 * GeometryColumns generated by hbm2java
 */
public class GeometryColumns implements java.io.Serializable {

	private GeometryColumnsId id;

	public GeometryColumns() {
	}

	public GeometryColumns(GeometryColumnsId id) {
		this.id = id;
	}

	public GeometryColumnsId getId() {
		return this.id;
	}

	public void setId(GeometryColumnsId id) {
		this.id = id;
	}

}
