package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * NumericValue generated by hbm2java
 */
public class NumericValue implements java.io.Serializable {
    
    private static final long serialVersionUID = 1L;

    private long numericValueId;

    private double value;

    private Set<Observation> observations = new HashSet<Observation>(0);

    public NumericValue() {
    }

    public NumericValue(long numericValueId, double value) {
        this.numericValueId = numericValueId;
        this.value = value;
    }

    public NumericValue(long numericValueId, double value, Set<Observation> observations) {
        this.numericValueId = numericValueId;
        this.value = value;
        this.observations = observations;
    }

    public long getNumericValueId() {
        return this.numericValueId;
    }

    public void setNumericValueId(long numericValueId) {
        this.numericValueId = numericValueId;
    }

    public double getValue() {
        return this.value;
    }

    public void setValue(double value) {
        this.value = value;
    }

    public Set<Observation> getObservations() {
        return this.observations;
    }

    public void setObservations(Set<Observation> observations) {
        this.observations = observations;
    }

}
