package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ObservationType generated by hbm2java
 */
public class ObservationType implements java.io.Serializable {

	private long observationTypeId;
	private String observationType;
	private Set procedures = new HashSet(0);
	private Set observationConstellations = new HashSet(0);

	public ObservationType() {
	}

	public ObservationType(long observationTypeId, String observationType) {
		this.observationTypeId = observationTypeId;
		this.observationType = observationType;
	}

	public ObservationType(long observationTypeId, String observationType,
			Set procedures, Set observationConstellations) {
		this.observationTypeId = observationTypeId;
		this.observationType = observationType;
		this.procedures = procedures;
		this.observationConstellations = observationConstellations;
	}

	public long getObservationTypeId() {
		return this.observationTypeId;
	}

	public void setObservationTypeId(long observationTypeId) {
		this.observationTypeId = observationTypeId;
	}

	public String getObservationType() {
		return this.observationType;
	}

	public void setObservationType(String observationType) {
		this.observationType = observationType;
	}

	public Set getProcedures() {
		return this.procedures;
	}

	public void setProcedures(Set procedures) {
		this.procedures = procedures;
	}

	public Set getObservationConstellations() {
		return this.observationConstellations;
	}

	public void setObservationConstellations(Set observationConstellations) {
		this.observationConstellations = observationConstellations;
	}

}
