package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ObservableProperty generated by hbm2java
 */
public class ObservableProperty implements java.io.Serializable {

	private long observablePropertyId;
	private ValueType valueType;
	private Unit unit;
	private String identifier;
	private String description;
	private Set requests = new HashSet(0);
	private Set compositePhenomenons = new HashSet(0);
	private Set observationConstellations = new HashSet(0);

	public ObservableProperty() {
	}

	public ObservableProperty(long observablePropertyId, ValueType valueType,
			Unit unit, String identifier) {
		this.observablePropertyId = observablePropertyId;
		this.valueType = valueType;
		this.unit = unit;
		this.identifier = identifier;
	}

	public ObservableProperty(long observablePropertyId, ValueType valueType,
			Unit unit, String identifier, String description, Set requests,
			Set compositePhenomenons, Set observationConstellations) {
		this.observablePropertyId = observablePropertyId;
		this.valueType = valueType;
		this.unit = unit;
		this.identifier = identifier;
		this.description = description;
		this.requests = requests;
		this.compositePhenomenons = compositePhenomenons;
		this.observationConstellations = observationConstellations;
	}

	public long getObservablePropertyId() {
		return this.observablePropertyId;
	}

	public void setObservablePropertyId(long observablePropertyId) {
		this.observablePropertyId = observablePropertyId;
	}

	public ValueType getValueType() {
		return this.valueType;
	}

	public void setValueType(ValueType valueType) {
		this.valueType = valueType;
	}

	public Unit getUnit() {
		return this.unit;
	}

	public void setUnit(Unit unit) {
		this.unit = unit;
	}

	public String getIdentifier() {
		return this.identifier;
	}

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getRequests() {
		return this.requests;
	}

	public void setRequests(Set requests) {
		this.requests = requests;
	}

	public Set getCompositePhenomenons() {
		return this.compositePhenomenons;
	}

	public void setCompositePhenomenons(Set compositePhenomenons) {
		this.compositePhenomenons = compositePhenomenons;
	}

	public Set getObservationConstellations() {
		return this.observationConstellations;
	}

	public void setObservationConstellations(Set observationConstellations) {
		this.observationConstellations = observationConstellations;
	}

}
