package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

/**
 * ObservationTemplate generated by hbm2java
 */
public class ObservationTemplate implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    private long observationNumericTemplateId;

    private Request request;

    private Procedure procedure;

    private String observationTemplate;

    public ObservationTemplate() {
    }

    public ObservationTemplate(long observationNumericTemplateId, Request request, Procedure procedure) {
        this.observationNumericTemplateId = observationNumericTemplateId;
        this.request = request;
        this.procedure = procedure;
    }

    public ObservationTemplate(long observationNumericTemplateId, Request request, Procedure procedure,
            String observationTemplate) {
        this.observationNumericTemplateId = observationNumericTemplateId;
        this.request = request;
        this.procedure = procedure;
        this.observationTemplate = observationTemplate;
    }

    public long getObservationNumericTemplateId() {
        return this.observationNumericTemplateId;
    }

    public void setObservationNumericTemplateId(long observationNumericTemplateId) {
        this.observationNumericTemplateId = observationNumericTemplateId;
    }

    public Request getRequest() {
        return this.request;
    }

    public void setRequest(Request request) {
        this.request = request;
    }

    public Procedure getProcedure() {
        return this.procedure;
    }

    public void setProcedure(Procedure procedure) {
        this.procedure = procedure;
    }

    public String getObservationTemplate() {
        return this.observationTemplate;
    }

    public void setObservationTemplate(String observationTemplate) {
        this.observationTemplate = observationTemplate;
    }

}
