package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Observation generated by hbm2java
 */
public class Observation implements java.io.Serializable {

	private long observationId;
	private FeatureOfInterest featureOfInterest;
	private ObservationConstellation observationConstellation;
	private String identifier;
	private Date phenomenonTimeStart;
	private Date phenomenonTimeEnd;
	private Date resultTime;
	private Date validTimeStart;
	private Date validTimeEnd;
	private Integer antiSubsetting;
	private Set spatialFilteringProfiles = new HashSet(0);
	private Set qualities = new HashSet(0);
	private Set countValues = new HashSet(0);
	private Set geometryValues = new HashSet(0);
	private Set categoryValues = new HashSet(0);
	private Set numericValues = new HashSet(0);
	private Set textValues = new HashSet(0);

	public Observation() {
	}

	public Observation(long observationId, FeatureOfInterest featureOfInterest,
			ObservationConstellation observationConstellation,
			Date phenomenonTimeStart) {
		this.observationId = observationId;
		this.featureOfInterest = featureOfInterest;
		this.observationConstellation = observationConstellation;
		this.phenomenonTimeStart = phenomenonTimeStart;
	}

	public Observation(long observationId, FeatureOfInterest featureOfInterest,
			ObservationConstellation observationConstellation,
			String identifier, Date phenomenonTimeStart,
			Date phenomenonTimeEnd, Date resultTime, Date validTimeStart,
			Date validTimeEnd, Integer antiSubsetting,
			Set spatialFilteringProfiles, Set qualities, Set countValues,
			Set geometryValues, Set categoryValues, Set numericValues,
			Set textValues) {
		this.observationId = observationId;
		this.featureOfInterest = featureOfInterest;
		this.observationConstellation = observationConstellation;
		this.identifier = identifier;
		this.phenomenonTimeStart = phenomenonTimeStart;
		this.phenomenonTimeEnd = phenomenonTimeEnd;
		this.resultTime = resultTime;
		this.validTimeStart = validTimeStart;
		this.validTimeEnd = validTimeEnd;
		this.antiSubsetting = antiSubsetting;
		this.spatialFilteringProfiles = spatialFilteringProfiles;
		this.qualities = qualities;
		this.countValues = countValues;
		this.geometryValues = geometryValues;
		this.categoryValues = categoryValues;
		this.numericValues = numericValues;
		this.textValues = textValues;
	}

	public long getObservationId() {
		return this.observationId;
	}

	public void setObservationId(long observationId) {
		this.observationId = observationId;
	}

	public FeatureOfInterest getFeatureOfInterest() {
		return this.featureOfInterest;
	}

	public void setFeatureOfInterest(FeatureOfInterest featureOfInterest) {
		this.featureOfInterest = featureOfInterest;
	}

	public ObservationConstellation getObservationConstellation() {
		return this.observationConstellation;
	}

	public void setObservationConstellation(
			ObservationConstellation observationConstellation) {
		this.observationConstellation = observationConstellation;
	}

	public String getIdentifier() {
		return this.identifier;
	}

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	public Date getPhenomenonTimeStart() {
		return this.phenomenonTimeStart;
	}

	public void setPhenomenonTimeStart(Date phenomenonTimeStart) {
		this.phenomenonTimeStart = phenomenonTimeStart;
	}

	public Date getPhenomenonTimeEnd() {
		return this.phenomenonTimeEnd;
	}

	public void setPhenomenonTimeEnd(Date phenomenonTimeEnd) {
		this.phenomenonTimeEnd = phenomenonTimeEnd;
	}

	public Date getResultTime() {
		return this.resultTime;
	}

	public void setResultTime(Date resultTime) {
		this.resultTime = resultTime;
	}

	public Date getValidTimeStart() {
		return this.validTimeStart;
	}

	public void setValidTimeStart(Date validTimeStart) {
		this.validTimeStart = validTimeStart;
	}

	public Date getValidTimeEnd() {
		return this.validTimeEnd;
	}

	public void setValidTimeEnd(Date validTimeEnd) {
		this.validTimeEnd = validTimeEnd;
	}

	public Integer getAntiSubsetting() {
		return this.antiSubsetting;
	}

	public void setAntiSubsetting(Integer antiSubsetting) {
		this.antiSubsetting = antiSubsetting;
	}

	public Set getSpatialFilteringProfiles() {
		return this.spatialFilteringProfiles;
	}

	public void setSpatialFilteringProfiles(Set spatialFilteringProfiles) {
		this.spatialFilteringProfiles = spatialFilteringProfiles;
	}

	public Set getQualities() {
		return this.qualities;
	}

	public void setQualities(Set qualities) {
		this.qualities = qualities;
	}

	public Set getCountValues() {
		return this.countValues;
	}

	public void setCountValues(Set countValues) {
		this.countValues = countValues;
	}

	public Set getGeometryValues() {
		return this.geometryValues;
	}

	public void setGeometryValues(Set geometryValues) {
		this.geometryValues = geometryValues;
	}

	public Set getCategoryValues() {
		return this.categoryValues;
	}

	public void setCategoryValues(Set categoryValues) {
		this.categoryValues = categoryValues;
	}

	public Set getNumericValues() {
		return this.numericValues;
	}

	public void setNumericValues(Set numericValues) {
		this.numericValues = numericValues;
	}

	public Set getTextValues() {
		return this.textValues;
	}

	public void setTextValues(Set textValues) {
		this.textValues = textValues;
	}

}
