package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

/**
 * ObservationTemplate generated by hbm2java
 */
public class ObservationTemplate implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    private long observationTemplateId;

    private Request request;

    private Procedure procedure;

    private String observationTemplate;

    public ObservationTemplate() {
    }

    public ObservationTemplate(long observationTemplateId, Request request, Procedure procedure) {
        this.observationTemplateId = observationTemplateId;
        this.request = request;
        this.procedure = procedure;
    }

    public ObservationTemplate(long observationTemplateId, Request request, Procedure procedure,
            String observationTemplate) {
        this.observationTemplateId = observationTemplateId;
        this.request = request;
        this.procedure = procedure;
        this.observationTemplate = observationTemplate;
    }

    public long getObservationTemplateId() {
        return this.observationTemplateId;
    }

    public void setObservationTemplateId(long observationTemplateId) {
        this.observationTemplateId = observationTemplateId;
    }

    public Request getRequest() {
        return this.request;
    }

    public void setRequest(Request request) {
        this.request = request;
    }

    public Procedure getProcedure() {
        return this.procedure;
    }

    public void setProcedure(Procedure procedure) {
        this.procedure = procedure;
    }

    public String getObservationTemplate() {
        return this.observationTemplate;
    }

    public void setObservationTemplate(String observationTemplate) {
        this.observationTemplate = observationTemplate;
    }

}
