package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Offering generated by hbm2java
 */
public class Offering implements java.io.Serializable {

	private long offeringId;
	private String identifier;
	private String name;
	private Set observationConstellations = new HashSet(0);
	private Set requests = new HashSet(0);
	private Set relatedFeatures = new HashSet(0);

	public Offering() {
	}

	public Offering(long offeringId, String identifier) {
		this.offeringId = offeringId;
		this.identifier = identifier;
	}

	public Offering(long offeringId, String identifier, String name,
			Set observationConstellations, Set requests, Set relatedFeatures) {
		this.offeringId = offeringId;
		this.identifier = identifier;
		this.name = name;
		this.observationConstellations = observationConstellations;
		this.requests = requests;
		this.relatedFeatures = relatedFeatures;
	}

	public long getOfferingId() {
		return this.offeringId;
	}

	public void setOfferingId(long offeringId) {
		this.offeringId = offeringId;
	}

	public String getIdentifier() {
		return this.identifier;
	}

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getObservationConstellations() {
		return this.observationConstellations;
	}

	public void setObservationConstellations(Set observationConstellations) {
		this.observationConstellations = observationConstellations;
	}

	public Set getRequests() {
		return this.requests;
	}

	public void setRequests(Set requests) {
		this.requests = requests;
	}

	public Set getRelatedFeatures() {
		return this.relatedFeatures;
	}

	public void setRelatedFeatures(Set relatedFeatures) {
		this.relatedFeatures = relatedFeatures;
	}

}
