package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Procedure generated by hbm2java
 */
public class Procedure implements java.io.Serializable {

	private long procedureId;
	private ProcedureDescriptionFormat procedureDescriptionFormat;
	private String identifier;
	private boolean deleted;
	private Set validProcedureTimes = new HashSet(0);
	private Set featureOfInterestTypes = new HashSet(0);
	private Set observationConstellations = new HashSet(0);
	private Set observationTypes = new HashSet(0);
	private Set proceduresForChildSensorId = new HashSet(0);
	private Set observationTemplates = new HashSet(0);
	private Set proceduresForParentSensorId = new HashSet(0);

	public Procedure() {
	}

	public Procedure(long procedureId,
			ProcedureDescriptionFormat procedureDescriptionFormat,
			String identifier, boolean deleted) {
		this.procedureId = procedureId;
		this.procedureDescriptionFormat = procedureDescriptionFormat;
		this.identifier = identifier;
		this.deleted = deleted;
	}

	public Procedure(long procedureId,
			ProcedureDescriptionFormat procedureDescriptionFormat,
			String identifier, boolean deleted, Set validProcedureTimes,
			Set featureOfInterestTypes, Set observationConstellations,
			Set observationTypes, Set proceduresForChildSensorId,
			Set observationTemplates, Set proceduresForParentSensorId) {
		this.procedureId = procedureId;
		this.procedureDescriptionFormat = procedureDescriptionFormat;
		this.identifier = identifier;
		this.deleted = deleted;
		this.validProcedureTimes = validProcedureTimes;
		this.featureOfInterestTypes = featureOfInterestTypes;
		this.observationConstellations = observationConstellations;
		this.observationTypes = observationTypes;
		this.proceduresForChildSensorId = proceduresForChildSensorId;
		this.observationTemplates = observationTemplates;
		this.proceduresForParentSensorId = proceduresForParentSensorId;
	}

	public long getProcedureId() {
		return this.procedureId;
	}

	public void setProcedureId(long procedureId) {
		this.procedureId = procedureId;
	}

	public ProcedureDescriptionFormat getProcedureDescriptionFormat() {
		return this.procedureDescriptionFormat;
	}

	public void setProcedureDescriptionFormat(
			ProcedureDescriptionFormat procedureDescriptionFormat) {
		this.procedureDescriptionFormat = procedureDescriptionFormat;
	}

	public String getIdentifier() {
		return this.identifier;
	}

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	public Set getValidProcedureTimes() {
		return this.validProcedureTimes;
	}

	public void setValidProcedureTimes(Set validProcedureTimes) {
		this.validProcedureTimes = validProcedureTimes;
	}

	public Set getFeatureOfInterestTypes() {
		return this.featureOfInterestTypes;
	}

	public void setFeatureOfInterestTypes(Set featureOfInterestTypes) {
		this.featureOfInterestTypes = featureOfInterestTypes;
	}

	public Set getObservationConstellations() {
		return this.observationConstellations;
	}

	public void setObservationConstellations(Set observationConstellations) {
		this.observationConstellations = observationConstellations;
	}

	public Set getObservationTypes() {
		return this.observationTypes;
	}

	public void setObservationTypes(Set observationTypes) {
		this.observationTypes = observationTypes;
	}

	public Set getProceduresForChildSensorId() {
		return this.proceduresForChildSensorId;
	}

	public void setProceduresForChildSensorId(Set proceduresForChildSensorId) {
		this.proceduresForChildSensorId = proceduresForChildSensorId;
	}

	public Set getObservationTemplates() {
		return this.observationTemplates;
	}

	public void setObservationTemplates(Set observationTemplates) {
		this.observationTemplates = observationTemplates;
	}

	public Set getProceduresForParentSensorId() {
		return this.proceduresForParentSensorId;
	}

	public void setProceduresForParentSensorId(Set proceduresForParentSensorId) {
		this.proceduresForParentSensorId = proceduresForParentSensorId;
	}

}
