package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ProcedureDescriptionFormat generated by hbm2java
 */
public class ProcedureDescriptionFormat implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    private long procedureDescriptionFormatId;

    private String procedureDescriptionFormat;

    private Set<Procedure> procedures = new HashSet<Procedure>(0);

    public ProcedureDescriptionFormat() {
    }

    public ProcedureDescriptionFormat(long procedureDescriptionFormatId, String procedureDescriptionFormat) {
        this.procedureDescriptionFormatId = procedureDescriptionFormatId;
        this.procedureDescriptionFormat = procedureDescriptionFormat;
    }

    public ProcedureDescriptionFormat(long procedureDescriptionFormatId, String procedureDescriptionFormat,
            Set<Procedure> procedures) {
        this.procedureDescriptionFormatId = procedureDescriptionFormatId;
        this.procedureDescriptionFormat = procedureDescriptionFormat;
        this.procedures = procedures;
    }

    public long getProcedureDescriptionFormatId() {
        return this.procedureDescriptionFormatId;
    }

    public void setProcedureDescriptionFormatId(long procedureDescriptionFormatId) {
        this.procedureDescriptionFormatId = procedureDescriptionFormatId;
    }

    public String getProcedureDescriptionFormat() {
        return this.procedureDescriptionFormat;
    }

    public void setProcedureDescriptionFormat(String procedureDescriptionFormat) {
        this.procedureDescriptionFormat = procedureDescriptionFormat;
    }

    public Set<Procedure> getProcedures() {
        return this.procedures;
    }

    public void setProcedures(Set<Procedure> procedures) {
        this.procedures = procedures;
    }

}
