package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * RelatedFeatureRole generated by hbm2java
 */
public class RelatedFeatureRole implements java.io.Serializable {

	private long relatedFeatureRoleId;
	private String relatedFeatureRole;
	private Set relatedFeatures = new HashSet(0);

	public RelatedFeatureRole() {
	}

	public RelatedFeatureRole(long relatedFeatureRoleId,
			String relatedFeatureRole) {
		this.relatedFeatureRoleId = relatedFeatureRoleId;
		this.relatedFeatureRole = relatedFeatureRole;
	}

	public RelatedFeatureRole(long relatedFeatureRoleId,
			String relatedFeatureRole, Set relatedFeatures) {
		this.relatedFeatureRoleId = relatedFeatureRoleId;
		this.relatedFeatureRole = relatedFeatureRole;
		this.relatedFeatures = relatedFeatures;
	}

	public long getRelatedFeatureRoleId() {
		return this.relatedFeatureRoleId;
	}

	public void setRelatedFeatureRoleId(long relatedFeatureRoleId) {
		this.relatedFeatureRoleId = relatedFeatureRoleId;
	}

	public String getRelatedFeatureRole() {
		return this.relatedFeatureRole;
	}

	public void setRelatedFeatureRole(String relatedFeatureRole) {
		this.relatedFeatureRole = relatedFeatureRole;
	}

	public Set getRelatedFeatures() {
		return this.relatedFeatures;
	}

	public void setRelatedFeatures(Set relatedFeatures) {
		this.relatedFeatures = relatedFeatures;
	}

}
