package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * RelatedFeature generated by hbm2java
 */
public class RelatedFeature implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    private long relatedFeatureId;

    private FeatureOfInterest featureOfInterest;

    private Set<RelatedFeatureRole> relatedFeatureRoles = new HashSet<RelatedFeatureRole>(0);

    private Set<Offering> offerings = new HashSet<Offering>(0);

    public RelatedFeature() {
    }

    public RelatedFeature(long relatedFeatureId) {
        this.relatedFeatureId = relatedFeatureId;
    }

    public RelatedFeature(long relatedFeatureId, FeatureOfInterest featureOfInterest, Set<RelatedFeatureRole> relatedFeatureRoles, Set<Offering> offerings) {
        this.relatedFeatureId = relatedFeatureId;
        this.featureOfInterest = featureOfInterest;
        this.relatedFeatureRoles = relatedFeatureRoles;
        this.offerings = offerings;
    }

    public long getRelatedFeatureId() {
        return this.relatedFeatureId;
    }

    public void setRelatedFeatureId(long relatedFeatureId) {
        this.relatedFeatureId = relatedFeatureId;
    }

    public FeatureOfInterest getFeatureOfInterest() {
        return this.featureOfInterest;
    }

    public void setFeatureOfInterest(FeatureOfInterest featureOfInterest) {
        this.featureOfInterest = featureOfInterest;
    }

    public Set<RelatedFeatureRole> getRelatedFeatureRoles() {
        return this.relatedFeatureRoles;
    }

    public void setRelatedFeatureRoles(Set<RelatedFeatureRole> relatedFeatureRoles) {
        this.relatedFeatureRoles = relatedFeatureRoles;
    }

    public Set<Offering> getOfferings() {
        return this.offerings;
    }

    public void setOfferings(Set<Offering> offerings) {
        this.offerings = offerings;
    }

}
