/**
 * Copyright (C) 2012
 * by 52 North Initiative for Geospatial Open Source Software GmbH
 *
 * Contact: Andreas Wytzisk
 * 52 North Initiative for Geospatial Open Source Software GmbH
 * Martin-Luther-King-Weg 24
 * 48155 Muenster, Germany
 * info@52north.org
 *
 * This program is free software; you can redistribute and/or modify it under
 * the terms of the GNU General Public License version 2 as published by the
 * Free Software Foundation.
 *
 * This program is distributed WITHOUT ANY WARRANTY; even without the implied
 * WARRANTY OF MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program (see gnu-gpl v2.txt). If not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA or
 * visit the Free Software Foundation web page, http://www.fsf.org.
 */
package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * RelatedFeatureRole generated by hbm2java
 */
public class RelatedFeatureRole implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    private long relatedFeatureRoleId;

    private String relatedFeatureRole;

    private Set<RelatedFeature> relatedFeatures = new HashSet<RelatedFeature>(0);

    public RelatedFeatureRole() {
    }

    public RelatedFeatureRole(long relatedFeatureRoleId, String relatedFeatureRole) {
        this.relatedFeatureRoleId = relatedFeatureRoleId;
        this.relatedFeatureRole = relatedFeatureRole;
    }

    public RelatedFeatureRole(long relatedFeatureRoleId, String relatedFeatureRole, Set<RelatedFeature> relatedFeatures) {
        this.relatedFeatureRoleId = relatedFeatureRoleId;
        this.relatedFeatureRole = relatedFeatureRole;
        this.relatedFeatures = relatedFeatures;
    }

    public long getRelatedFeatureRoleId() {
        return this.relatedFeatureRoleId;
    }

    public void setRelatedFeatureRoleId(long relatedFeatureRoleId) {
        this.relatedFeatureRoleId = relatedFeatureRoleId;
    }

    public String getRelatedFeatureRole() {
        return this.relatedFeatureRole;
    }

    public void setRelatedFeatureRole(String relatedFeatureRole) {
        this.relatedFeatureRole = relatedFeatureRole;
    }

    public Set<RelatedFeature> getRelatedFeatures() {
        return this.relatedFeatures;
    }

    public void setRelatedFeatures(Set<RelatedFeature> relatedFeatures) {
        this.relatedFeatures = relatedFeatures;
    }

}
