/**
 * Copyright (C) 2013
 * by 52 North Initiative for Geospatial Open Source Software GmbH
 *
 * Contact: Andreas Wytzisk
 * 52 North Initiative for Geospatial Open Source Software GmbH
 * Martin-Luther-King-Weg 24
 * 48155 Muenster, Germany
 * info@52north.org
 *
 * This program is free software; you can redistribute and/or modify it under
 * the terms of the GNU General Public License version 2 as published by the
 * Free Software Foundation.
 *
 * This program is distributed WITHOUT ANY WARRANTY; even without the implied
 * WARRANTY OF MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program (see gnu-gpl v2.txt). If not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA or
 * visit the Free Software Foundation web page, http://www.fsf.org.
 */
package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * RelatedFeature generated by hbm2java
 */
public class RelatedFeature implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    private long relatedFeatureId;

    private FeatureOfInterest featureOfInterest;

    private Set<RelatedFeatureRole> relatedFeatureRoles = new HashSet<RelatedFeatureRole>(0);

//    private Set<Offering> offerings = new HashSet<Offering>(0);

    public RelatedFeature() {
    }

//    public RelatedFeature(long relatedFeatureId) {
//        this.relatedFeatureId = relatedFeatureId;
//    }
//
//    public RelatedFeature(long relatedFeatureId, FeatureOfInterest featureOfInterest, Set<RelatedFeatureRole> relatedFeatureRoles, Set<Offering> offerings) {
//        this.relatedFeatureId = relatedFeatureId;
//        this.featureOfInterest = featureOfInterest;
//        this.relatedFeatureRoles = relatedFeatureRoles;
//        this.offerings = offerings;
//    }

    public long getRelatedFeatureId() {
        return this.relatedFeatureId;
    }

    public void setRelatedFeatureId(long relatedFeatureId) {
        this.relatedFeatureId = relatedFeatureId;
    }

    public FeatureOfInterest getFeatureOfInterest() {
        return this.featureOfInterest;
    }

    public void setFeatureOfInterest(FeatureOfInterest featureOfInterest) {
        this.featureOfInterest = featureOfInterest;
    }

    public Set<RelatedFeatureRole> getRelatedFeatureRoles() {
        return this.relatedFeatureRoles;
    }

    public void setRelatedFeatureRoles(Set<RelatedFeatureRole> relatedFeatureRoles) {
        this.relatedFeatureRoles = relatedFeatureRoles;
    }

//    public Set<Offering> getOfferings() {
//        return this.offerings;
//    }
//
//    public void setOfferings(Set<Offering> offerings) {
//        this.offerings = offerings;
//    }

}
