package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Request generated by hbm2java
 */
public class Request implements java.io.Serializable {

	private long requestId;
	private Offering offering;
	private String request;
	private Date beginLease;
	private Date endLease;
	private Set observableProperties = new HashSet(0);
	private Set observationTemplates = new HashSet(0);
	private Set compositePhenomenons = new HashSet(0);

	public Request() {
	}

	public Request(long requestId, Offering offering, String request,
			Date endLease) {
		this.requestId = requestId;
		this.offering = offering;
		this.request = request;
		this.endLease = endLease;
	}

	public Request(long requestId, Offering offering, String request,
			Date beginLease, Date endLease, Set observableProperties,
			Set observationTemplates, Set compositePhenomenons) {
		this.requestId = requestId;
		this.offering = offering;
		this.request = request;
		this.beginLease = beginLease;
		this.endLease = endLease;
		this.observableProperties = observableProperties;
		this.observationTemplates = observationTemplates;
		this.compositePhenomenons = compositePhenomenons;
	}

	public long getRequestId() {
		return this.requestId;
	}

	public void setRequestId(long requestId) {
		this.requestId = requestId;
	}

	public Offering getOffering() {
		return this.offering;
	}

	public void setOffering(Offering offering) {
		this.offering = offering;
	}

	public String getRequest() {
		return this.request;
	}

	public void setRequest(String request) {
		this.request = request;
	}

	public Date getBeginLease() {
		return this.beginLease;
	}

	public void setBeginLease(Date beginLease) {
		this.beginLease = beginLease;
	}

	public Date getEndLease() {
		return this.endLease;
	}

	public void setEndLease(Date endLease) {
		this.endLease = endLease;
	}

	public Set getObservableProperties() {
		return this.observableProperties;
	}

	public void setObservableProperties(Set observableProperties) {
		this.observableProperties = observableProperties;
	}

	public Set getObservationTemplates() {
		return this.observationTemplates;
	}

	public void setObservationTemplates(Set observationTemplates) {
		this.observationTemplates = observationTemplates;
	}

	public Set getCompositePhenomenons() {
		return this.compositePhenomenons;
	}

	public void setCompositePhenomenons(Set compositePhenomenons) {
		this.compositePhenomenons = compositePhenomenons;
	}

}
