package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ResultType generated by hbm2java
 */
public class ResultType implements java.io.Serializable {

	private long resultTypeId;
	private String resultType;
	private Set observationConstellations = new HashSet(0);

	public ResultType() {
	}

	public ResultType(long resultTypeId, String resultType) {
		this.resultTypeId = resultTypeId;
		this.resultType = resultType;
	}

	public ResultType(long resultTypeId, String resultType,
			Set observationConstellations) {
		this.resultTypeId = resultTypeId;
		this.resultType = resultType;
		this.observationConstellations = observationConstellations;
	}

	public long getResultTypeId() {
		return this.resultTypeId;
	}

	public void setResultTypeId(long resultTypeId) {
		this.resultTypeId = resultTypeId;
	}

	public String getResultType() {
		return this.resultType;
	}

	public void setResultType(String resultType) {
		this.resultType = resultType;
	}

	public Set getObservationConstellations() {
		return this.observationConstellations;
	}

	public void setObservationConstellations(Set observationConstellations) {
		this.observationConstellations = observationConstellations;
	}

}
