package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ResultStructureType generated by hbm2java
 */
public class ResultStructureType implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    private long resultStructureTypeId;

    private String resultStructureType;

    private Set<ResultTemplate> resultTemplates = new HashSet<ResultTemplate>(0);

    public ResultStructureType() {
    }

    public ResultStructureType(long resultStructureTypeId, String resultStructureType) {
        this.resultStructureTypeId = resultStructureTypeId;
        this.resultStructureType = resultStructureType;
    }

    public ResultStructureType(long resultStructureTypeId, String resultStructureType, Set<ResultTemplate> resultTemplates) {
        this.resultStructureTypeId = resultStructureTypeId;
        this.resultStructureType = resultStructureType;
        this.resultTemplates = resultTemplates;
    }

    public long getResultStructureTypeId() {
        return this.resultStructureTypeId;
    }

    public void setResultStructureTypeId(long resultStructureTypeId) {
        this.resultStructureTypeId = resultStructureTypeId;
    }

    public String getResultStructureType() {
        return this.resultStructureType;
    }

    public void setResultStructureType(String resultStructureType) {
        this.resultStructureType = resultStructureType;
    }

    public Set<ResultTemplate> getResultTemplates() {
        return this.resultTemplates;
    }

    public void setResultTemplates(Set<ResultTemplate> resultTemplates) {
        this.resultTemplates = resultTemplates;
    }

}
