/**
 * Copyright (C) 2012
 * by 52 North Initiative for Geospatial Open Source Software GmbH
 *
 * Contact: Andreas Wytzisk
 * 52 North Initiative for Geospatial Open Source Software GmbH
 * Martin-Luther-King-Weg 24
 * 48155 Muenster, Germany
 * info@52north.org
 *
 * This program is free software; you can redistribute and/or modify it under
 * the terms of the GNU General Public License version 2 as published by the
 * Free Software Foundation.
 *
 * This program is distributed WITHOUT ANY WARRANTY; even without the implied
 * WARRANTY OF MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program (see gnu-gpl v2.txt). If not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA or
 * visit the Free Software Foundation web page, http://www.fsf.org.
 */
package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

/**
 * ResultTemplate generated by hbm2java
 */
public class ResultTemplate implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    private long resultTemplateId;

    private FeatureOfInterest featureOfInterest;

    private ObservationConstellation observationConstellation;

    private String identifier;

    private String resultStructure;

    private String resultEncoding;

    public ResultTemplate() {
    }

    public ResultTemplate(long resultTemplateId, FeatureOfInterest featureOfInterest,
            ObservationConstellation observationConstellation, String identifier, String resultStructure,
            String resultEncoding) {
        this.resultTemplateId = resultTemplateId;
        this.featureOfInterest = featureOfInterest;
        this.observationConstellation = observationConstellation;
        this.identifier = identifier;
        this.resultStructure = resultStructure;
        this.resultEncoding = resultEncoding;
    }

    public long getResultTemplateId() {
        return this.resultTemplateId;
    }

    public void setResultTemplateId(long resultTemplateId) {
        this.resultTemplateId = resultTemplateId;
    }

    public FeatureOfInterest getFeatureOfInterest() {
        return this.featureOfInterest;
    }

    public void setFeatureOfInterest(FeatureOfInterest featureOfInterest) {
        this.featureOfInterest = featureOfInterest;
    }

    public ObservationConstellation getObservationConstellation() {
        return this.observationConstellation;
    }

    public void setObservationConstellation(ObservationConstellation observationConstellation) {
        this.observationConstellation = observationConstellation;
    }

    public String getIdentifier() {
        return this.identifier;
    }

    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    public String getResultStructure() {
        return this.resultStructure;
    }

    public void setResultStructure(String resultStructure) {
        this.resultStructure = resultStructure;
    }

    public String getResultEncoding() {
        return this.resultEncoding;
    }

    public void setResultEncoding(String resultEncoding) {
        this.resultEncoding = resultEncoding;
    }

}
