package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

/**
 * ResultTemplate generated by hbm2java
 */
public class ResultTemplate implements java.io.Serializable {

	private long resultTemplateId;
	private ResultStructureType resultStructureType;
	private FeatureOfInterest featureOfInterest;
	private ObservationConstellation observationConstellation;
	private String identifier;
	private String resultStructure;
	private String resultEncoding;

	public ResultTemplate() {
	}

	public ResultTemplate(long resultTemplateId,
			ResultStructureType resultStructureType,
			FeatureOfInterest featureOfInterest,
			ObservationConstellation observationConstellation,
			String identifier, String resultStructure, String resultEncoding) {
		this.resultTemplateId = resultTemplateId;
		this.resultStructureType = resultStructureType;
		this.featureOfInterest = featureOfInterest;
		this.observationConstellation = observationConstellation;
		this.identifier = identifier;
		this.resultStructure = resultStructure;
		this.resultEncoding = resultEncoding;
	}

	public long getResultTemplateId() {
		return this.resultTemplateId;
	}

	public void setResultTemplateId(long resultTemplateId) {
		this.resultTemplateId = resultTemplateId;
	}

	public ResultStructureType getResultStructureType() {
		return this.resultStructureType;
	}

	public void setResultStructureType(ResultStructureType resultStructureType) {
		this.resultStructureType = resultStructureType;
	}

	public FeatureOfInterest getFeatureOfInterest() {
		return this.featureOfInterest;
	}

	public void setFeatureOfInterest(FeatureOfInterest featureOfInterest) {
		this.featureOfInterest = featureOfInterest;
	}

	public ObservationConstellation getObservationConstellation() {
		return this.observationConstellation;
	}

	public void setObservationConstellation(
			ObservationConstellation observationConstellation) {
		this.observationConstellation = observationConstellation;
	}

	public String getIdentifier() {
		return this.identifier;
	}

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	public String getResultStructure() {
		return this.resultStructure;
	}

	public void setResultStructure(String resultStructure) {
		this.resultStructure = resultStructure;
	}

	public String getResultEncoding() {
		return this.resultEncoding;
	}

	public void setResultEncoding(String resultEncoding) {
		this.resultEncoding = resultEncoding;
	}

}
