/**
 * Copyright (C) 2012
 * by 52 North Initiative for Geospatial Open Source Software GmbH
 *
 * Contact: Andreas Wytzisk
 * 52 North Initiative for Geospatial Open Source Software GmbH
 * Martin-Luther-King-Weg 24
 * 48155 Muenster, Germany
 * info@52north.org
 *
 * This program is free software; you can redistribute and/or modify it under
 * the terms of the GNU General Public License version 2 as published by the
 * Free Software Foundation.
 *
 * This program is distributed WITHOUT ANY WARRANTY; even without the implied
 * WARRANTY OF MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program (see gnu-gpl v2.txt). If not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA or
 * visit the Free Software Foundation web page, http://www.fsf.org.
 */
package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.vividsolutions.jts.geom.Geometry;

/**
 * SpatialFilteringProfile generated by hbm2java
 */
public class SpatialFilteringProfile implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    private long spatialFilteringProfileId;

    private String identifier;

    private Geometry geom;

    private Set<Observation> observations = new HashSet<Observation>(0);

    public SpatialFilteringProfile() {
    }

    public SpatialFilteringProfile(long spatialFilteringProfileId, String identifier, Geometry geom) {
        this.spatialFilteringProfileId = spatialFilteringProfileId;
        this.identifier = identifier;
        this.geom = geom;
    }

    public SpatialFilteringProfile(long spatialFilteringProfileId, String identifier, Geometry geom, Set<Observation> observations) {
        this.spatialFilteringProfileId = spatialFilteringProfileId;
        this.identifier = identifier;
        this.geom = geom;
        this.observations = observations;
    }

    public long getSpatialFilteringProfileId() {
        return this.spatialFilteringProfileId;
    }

    public void setSpatialFilteringProfileId(long spatialFilteringProfileId) {
        this.spatialFilteringProfileId = spatialFilteringProfileId;
    }

    public String getIdentifier() {
        return this.identifier;
    }

    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    public Geometry getGeom() {
        return this.geom;
    }

    public void setGeom(Geometry geom) {
        this.geom = geom;
    }

    public Set<Observation> getObservations() {
        return this.observations;
    }

    public void setObservations(Set<Observation> observations) {
        this.observations = observations;
    }

}
