package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.vividsolutions.jts.geom.Geometry;

/**
 * SpatialFilteringProfile generated by hbm2java
 */
public class SpatialFilteringProfile implements java.io.Serializable {

	private long spatialFilteringProfileId;
	private String identifier;
	private Geometry geom;
	private Set observations = new HashSet(0);

	public SpatialFilteringProfile() {
	}

	public SpatialFilteringProfile(long spatialFilteringProfileId,
			String identifier, Geometry geom) {
		this.spatialFilteringProfileId = spatialFilteringProfileId;
		this.identifier = identifier;
		this.geom = geom;
	}

	public SpatialFilteringProfile(long spatialFilteringProfileId,
			String identifier, Geometry geom, Set observations) {
		this.spatialFilteringProfileId = spatialFilteringProfileId;
		this.identifier = identifier;
		this.geom = geom;
		this.observations = observations;
	}

	public long getSpatialFilteringProfileId() {
		return this.spatialFilteringProfileId;
	}

	public void setSpatialFilteringProfileId(long spatialFilteringProfileId) {
		this.spatialFilteringProfileId = spatialFilteringProfileId;
	}

	public String getIdentifier() {
		return this.identifier;
	}

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	public Geometry getGeom() {
		return this.geom;
	}

	public void setGeom(Geometry geom) {
		this.geom = geom;
	}

	public Set getObservations() {
		return this.observations;
	}

	public void setObservations(Set observations) {
		this.observations = observations;
	}

}
