package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1


/**
 * SweType generated by hbm2java
 */
public class SweType implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    private long sweTypeId;

    private String sweType;

    public SweType() {
    }

    public SweType(long sweTypeId, String sweType) {
        this.sweTypeId = sweTypeId;
        this.sweType = sweType;
    }

    public long getSweTypeId() {
        return this.sweTypeId;
    }

    public void setSweTypeId(long sweTypeId) {
        this.sweTypeId = sweTypeId;
    }

    public String getSweType() {
        return this.sweType;
    }

    public void setSweType(String sweType) {
        this.sweType = sweType;
    }

}
