package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TextValue generated by hbm2java
 */
public class TextValue implements java.io.Serializable {
    
    private static final long serialVersionUID = 1L;

    private long textValueId;

    private String value;

    private Set<Observation> observations = new HashSet<Observation>(0);

    public TextValue() {
    }

    public TextValue(long textValueId, String value) {
        this.textValueId = textValueId;
        this.value = value;
    }

    public TextValue(long textValueId, String value, Set<Observation> observations) {
        this.textValueId = textValueId;
        this.value = value;
        this.observations = observations;
    }

    public long getTextValueId() {
        return this.textValueId;
    }

    public void setTextValueId(long textValueId) {
        this.textValueId = textValueId;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Set<Observation> getObservations() {
        return this.observations;
    }

    public void setObservations(Set<Observation> observations) {
        this.observations = observations;
    }

}
