package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1


/**
 * Unit generated by hbm2java
 */
public class Unit implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    private long unitId;

    private String unit;

    public Unit() {
    }

    public Unit(long unitId, String unit) {
        this.unitId = unitId;
        this.unit = unit;
    }

    public long getUnitId() {
        return this.unitId;
    }

    public void setUnitId(long unitId) {
        this.unitId = unitId;
    }

    public String getUnit() {
        return this.unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

}
