package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Unit generated by hbm2java
 */
public class Unit implements java.io.Serializable {

	private long unitId;
	private String unit;
	private Set qualities = new HashSet(0);
	private Set observableProperties = new HashSet(0);

	public Unit() {
	}

	public Unit(long unitId, String unit) {
		this.unitId = unitId;
		this.unit = unit;
	}

	public Unit(long unitId, String unit, Set qualities,
			Set observableProperties) {
		this.unitId = unitId;
		this.unit = unit;
		this.qualities = qualities;
		this.observableProperties = observableProperties;
	}

	public long getUnitId() {
		return this.unitId;
	}

	public void setUnitId(long unitId) {
		this.unitId = unitId;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public Set getQualities() {
		return this.qualities;
	}

	public void setQualities(Set qualities) {
		this.qualities = qualities;
	}

	public Set getObservableProperties() {
		return this.observableProperties;
	}

	public void setObservableProperties(Set observableProperties) {
		this.observableProperties = observableProperties;
	}

}
