package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ValidProcedureTime generated by hbm2java
 */
public class ValidProcedureTime implements java.io.Serializable {

	private long validProcedureTimeId;
	private Procedure procedure;
	private Date startTime;
	private Date endTime;
	private String descriptionUrl;
	private String descriptionXml;

	public ValidProcedureTime() {
	}

	public ValidProcedureTime(long validProcedureTimeId, Procedure procedure,
			Date startTime) {
		this.validProcedureTimeId = validProcedureTimeId;
		this.procedure = procedure;
		this.startTime = startTime;
	}

	public ValidProcedureTime(long validProcedureTimeId, Procedure procedure,
			Date startTime, Date endTime, String descriptionUrl,
			String descriptionXml) {
		this.validProcedureTimeId = validProcedureTimeId;
		this.procedure = procedure;
		this.startTime = startTime;
		this.endTime = endTime;
		this.descriptionUrl = descriptionUrl;
		this.descriptionXml = descriptionXml;
	}

	public long getValidProcedureTimeId() {
		return this.validProcedureTimeId;
	}

	public void setValidProcedureTimeId(long validProcedureTimeId) {
		this.validProcedureTimeId = validProcedureTimeId;
	}

	public Procedure getProcedure() {
		return this.procedure;
	}

	public void setProcedure(Procedure procedure) {
		this.procedure = procedure;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public String getDescriptionUrl() {
		return this.descriptionUrl;
	}

	public void setDescriptionUrl(String descriptionUrl) {
		this.descriptionUrl = descriptionUrl;
	}

	public String getDescriptionXml() {
		return this.descriptionXml;
	}

	public void setDescriptionXml(String descriptionXml) {
		this.descriptionXml = descriptionXml;
	}

}
