package org.n52.sos.ds.hibernate.entities;

// Generated 10.07.2012 15:18:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ValueType generated by hbm2java
 */
public class ValueType implements java.io.Serializable {

	private long valueTypeId;
	private String valueType;
	private Set observableProperties = new HashSet(0);

	public ValueType() {
	}

	public ValueType(long valueTypeId, String valueType) {
		this.valueTypeId = valueTypeId;
		this.valueType = valueType;
	}

	public ValueType(long valueTypeId, String valueType,
			Set observableProperties) {
		this.valueTypeId = valueTypeId;
		this.valueType = valueType;
		this.observableProperties = observableProperties;
	}

	public long getValueTypeId() {
		return this.valueTypeId;
	}

	public void setValueTypeId(long valueTypeId) {
		this.valueTypeId = valueTypeId;
	}

	public String getValueType() {
		return this.valueType;
	}

	public void setValueType(String valueType) {
		this.valueType = valueType;
	}

	public Set getObservableProperties() {
		return this.observableProperties;
	}

	public void setObservableProperties(Set observableProperties) {
		this.observableProperties = observableProperties;
	}

}
